# Generated by Django 5.2 on 2025-04-16 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_order_farmer_payment_product_order_product_vendor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="user",
        ),
        migrations.RenameField(
            model_name="farmer",
            old_name="created_at",
            new_name="joined_on",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="location",
        ),
        migrations.AddField(
            model_name="farmer",
            name="address",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="farmer_profiles/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("FRUIT", "Fruit"),
                    ("VEGETABLE", "Vegetable"),
                    ("GRAIN", "Grain"),
                    ("PULSE", "Pulse"),
                    ("SPICE", "Spice"),
                    ("DAIRY", "Dairy"),
                    ("HERB", "Herb"),
                    ("TUBER", "Tuber"),
                    ("FLOWER", "Flower"),
                    ("OILSEED", "Oilseed"),
                    ("NUT", "Nut"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(help_text="e.g. kg, litre, bundle", max_length=50),
        ),
        migrations.CreateModel(
            name="FarmerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_sold", models.PositiveIntegerField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("buyer_name", models.CharField(max_length=255)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.farmer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
